// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	dto "golang/module/transaction/dto"
	entities "golang/module/transaction/entities"

	mock "github.com/stretchr/testify/mock"
)

// RepositoryInterface is an autogenerated mock type for the RepositoryInterface type
type RepositoryInterface struct {
	mock.Mock
}

type RepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *RepositoryInterface) EXPECT() *RepositoryInterface_Expecter {
	return &RepositoryInterface_Expecter{mock: &_m.Mock}
}

// GetAllTransaction provides a mock function with given fields: req
func (_m *RepositoryInterface) GetAllTransaction(req *dto.Request) ([]entities.Transaction, error, int64) {
	ret := _m.Called(req)

	var r0 []entities.Transaction
	var r1 error
	var r2 int64
	if rf, ok := ret.Get(0).(func(*dto.Request) ([]entities.Transaction, error, int64)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(*dto.Request) []entities.Transaction); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(*dto.Request) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(*dto.Request) int64); ok {
		r2 = rf(req)
	} else {
		r2 = ret.Get(2).(int64)
	}

	return r0, r1, r2
}

// RepositoryInterface_GetAllTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTransaction'
type RepositoryInterface_GetAllTransaction_Call struct {
	*mock.Call
}

// GetAllTransaction is a helper method to define mock.On call
//   - req *dto.Request
func (_e *RepositoryInterface_Expecter) GetAllTransaction(req interface{}) *RepositoryInterface_GetAllTransaction_Call {
	return &RepositoryInterface_GetAllTransaction_Call{Call: _e.mock.On("GetAllTransaction", req)}
}

func (_c *RepositoryInterface_GetAllTransaction_Call) Run(run func(req *dto.Request)) *RepositoryInterface_GetAllTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*dto.Request))
	})
	return _c
}

func (_c *RepositoryInterface_GetAllTransaction_Call) Return(_a0 []entities.Transaction, _a1 error, _a2 int64) *RepositoryInterface_GetAllTransaction_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *RepositoryInterface_GetAllTransaction_Call) RunAndReturn(run func(*dto.Request) ([]entities.Transaction, error, int64)) *RepositoryInterface_GetAllTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepositoryInterface creates a new instance of RepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryInterface {
	mock := &RepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
